services:
  apigateway:
    container_name: apigateway
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - rabbitmq
      - pg_db
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  identity:
    container_name: identity
    image: identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
    ports:
      - 5002:80
      - 5003:443
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  tdonation:
    container_name: tdonation
    image: tdonation
    build:
      context: .
      dockerfile: TDonation/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=pg_db;Port=5432;Database=donationdb;Username=postgres;Password=postgres
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5004:80
      - 5005:443
    depends_on:
      - rabbitmq
      - pg_db
    volumes:
      - ~/.aspnet/https:/https:ro

  tpostservice:
    container_name: tpostservice
    image: tpostservice
    build:
      context: .
      dockerfile: TPostService/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=pg_db;Port=5432;Database=postdb;Username=postgres;Password=postgres
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5006:80
      - 5007:443
    depends_on:
      - rabbitmq
      - pg_db
    volumes:
      - ~/.aspnet/https:/https:ro

  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    image: rabbitmq:3-management
    
  pg_db:
    image: postgres:latest
    container_name: pg_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always